### ISSUE TITLE
Vertices with duplicated labels not shown in DOT visualisation

### ISSUE THREAD

**Issue by louismrose** [monora/rgl#15]
Suppose we have the following graph containing 3 vertices:

```ruby
class Person
  attr_reader :name
  def initialize(name)
    @name = name
  end

  def to_s
    name
  end
end

dg=RGL::DirectedAdjacencyGraph.new
dg.add_vertex(Person.new("Alice"))
dg.add_vertex(Person.new("Bob"))
dg.add_vertex(Person.new("Alice"))
```

When the graph is visualised via `dg.write_to_graphic_file('jpg')` it has only two vertices:

![graph](https://cloud.githubusercontent.com/assets/77096/6151895/e171d20e-b210-11e4-85af-dc92b3283329.jpg)

**Comment by monora** [comment]
Thank you for this patch. I added Graph#vertex_label to be more flexible for showing graph vertex labels.

**Comment by louismrose** [comment]
Looks great -- thanks. And thanks for maintaining this fantastic gem!
