### ISSUE TITLE
Dependency on algorithms

### ISSUE THREAD

**Issue by fluke777** [monora/rgl#17]
Would it be possible to bump the algorithms gem to 6.x? I think they added support for JRuby. It would be awesome to have this great gem available for JRuby as well.

**Comment by Ch4s3** [comment]
I did this in #18 and added support for newer rubies. Hopefully @monora will have time to take a look.

**Comment by fluke777** [comment]
@Ch4s3 Awesome, thanks

**Comment by Ch4s3** [comment]
@fluke777 np

**Comment by monora** [comment]
Thanks for this improvement.

**Comment by monora** [comment]
Thanks for this improvement.
