### ISSUE TITLE
New tagged version

### ISSUE THREAD

**Issue by Ch4s3** [monora/rgl#19]
There have been a handful of changes since the last tagged version, and a v0.6.0 would be nice.

**Comment by monora** [comment]
OK, I would prefer a v0.5.1 since we have no functional additions. I will look into this in the next days.

**Comment by Ch4s3** [comment]
v0.5.1 sounds fine to me, I'm just interested in pointing my gemfile to a specific version that has jRuby support.

**Comment by monora** [comment]
Release done. See https://rubygems.org/gems/rgl/versions/0.5.1

**Comment by Ch4s3** [comment]
Awesome, thanks!
