### ISSUE TITLE
Spurious nodes in DOT when vertices are strings

### ISSUE THREAD

**Issue by jonahb** [monora/rgl#21]
````ruby
require 'rgl/adjacency'
require 'rgl/dot'

puts RGL::DirectedAdjacencyGraph["a", "b"].to_dot_graph
````

Output:
````
digraph RGL__DirectedAdjacencyGraph {
    70319033367680 [
        fontsize = 8,
        label = a
    ]

    70319033367400 [
        fontsize = 8,
        label = b
    ]

    70319033367680 -> 70319033367380 [
        fontsize = 8
    ]
}
````

Note the extra node; the "b" node is given a new name in the edge definition.

This happens because the adjacency list for each vertex is stored as a Set. Set uses Hash as internal storage, and Hash copies non-frozen string keys. Therefore when "b" is added to the adjacency list of "a," a new object is created. The DOT module (dot.rb) uses the Ruby object ID as the node name and therefore generates two "b" nodes.

dot.rb should probably be changed not to use object_id, for consistency with the rest of the library.

**Comment by monora** [comment]
@jonahb thank you for your bug report. I implemented this a you suggested. You can now use your own vertex_id function as shown in dot_test.rb:

```ruby
  def test_to_dot_graph
    graph = RGL::AdjacencyGraph["a", "b"]
    def graph.vertex_label(v)
      "label-"+v.to_s
    end

    def graph.vertex_id(v)
      "id-"+v.to_s
    end
    dot = graph.write_to_graphic_file
  end
```

Default is:

```ruby
    def vertex_id(v)
      v
    end
```
which solves your problem if vertices are strings.

**Comment by jonahb** [comment]
Works for me now. Thanks.
