### ISSUE TITLE
Is rgl thread safe?

### ISSUE THREAD

**Issue by tuzz** [monora/rgl#29]
Hi - thanks for supporting a great library.

We're thinking of using rgl on one of our projects and we were wondering whether it's thread safe?

Thanks

**Comment by monora** [comment]
Glad to hear that you are interested in RGL. As far as I know, RGL is as thread safe as the ruby data structures it is using (mainly hash maps and sets). There should be no global state in any of the algorithms and data structures. I think we do not have any algorithms using concurrency. Nevertheless you should inspect the code, which you plan to use.

@KL-7 has contributed a big part of the library, which I do not overview completely. Perhaps he could also comment on your question.

**Comment by monora** [comment]
@tuzz Are you satisfied with this answer? Do you use RGL in your project. If so, did you have problems concerning thread safety?

**Comment by tuzz** [comment]
Many thanks for your responses. We decided to go with another approach in the end.

Much appreciated.
