### ISSUE TITLE
DOT keywords as labels cause DOT syntax errors

### ISSUE THREAD

**Issue by kjhenner** [monora/rgl#31]
The keywords node, edge, graph, digraph, subgraph, and strict (case insensitive) cause syntax errors in the DOT format when they're used as labels.

The DOT language documentation notes that: 'There is no semantic difference between abc_2 and "abc_2", or between 2.34 and "2.34". Obviously, to use a keyword as an ID, it must be quoted.' (http://www.graphviz.org/doc/info/lang.html) As far as I can tell, the same applies to labels. If this is the case, it seems that it would be best to double-quote all labels generated by the to_dot_graph function and escape any double-quotes in the labels themselves.

**Comment by monora** [comment]
I am not sure, if I understand the problem correctly. Can you provide a test case or example graph, which causes problems when exported to dot. Which RGL version did you use? With commits fa759290 and 33206f we changed exporting to dot.

**Comment by monora** [comment]
@kjhenner did you check if your problem is fixed with the current development branch? Can we then close this issue?

**Comment by monora** [comment]
@kjhenner I would like to close this issue. Could you answer my question above.
