### ISSUE TITLE
write_to_graphic_file('jpg') does not produce a jpg file

### ISSUE THREAD

**Issue by wesm-outreach** [monora/rgl#38]
I ran the below example from the readme verbatim, and I did not got a `graph.jpg` file, instead it created a `graph.dot` file.

### Example from README.md
```
irb> require 'rgl/adjacency'
irb> dg=RGL::DirectedAdjacencyGraph[1,2 ,2,3 ,2,4, 4,5, 6,4, 1,6]
# Use DOT to visualize this graph:
irb> require 'rgl/dot'
irb> dg.write_to_graphic_file('jpg')
"graph.jpg"
```

**Comment by monora** [comment]
The call should produce both files (rgl creates the dot file and than calls dot to produce th jpg file). I just reproduced this behavior. Could you please check, if graph.jpg is has also been created.

**Comment by wesm-outreach** [comment]
after reading the code, it seems I need a binary installed
```
# Call dotty[http://www.graphviz.org] for the graph which is written to the
# file 'graph.dot' in the current directory.# Call dotty[http://www.graphviz.org] for the graph which is written to the
# file 'graph.dot' in the current directory.
```

this should probably be called out in readme and/or some error handling in case `dotty` is not installed.
