### ISSUE TITLE
Rubygems release?

### ISSUE THREAD

**Issue by krallin** [monora/rgl#39]
Hi there,

Just curious if you had plans to make a new Rubygems release?

We have a library we'd like to open-source that depends on rgl, but would like to ensure that users that adopt this library don't run into this (fixed) bug: https://github.com/monora/rgl/pull/36 😄 

Thanks!

**Comment by monora** [comment]
New release 0.5.3 is out.

**Comment by krallin** [comment]
Thanks @monora!
