### ISSUE TITLE
How to find the longest path between 2 vertices ?

### ISSUE THREAD

**Issue by rtcoms** [monora/rgl#40]
@monora Thanks for your effort to create this gem.

The solution I found that to use -ve weight for edges and then find shortest path and that will be equal to longest path. In docs I found that -ve weight for edges will return error for various shortest path algorithm methods. 

How should I overcome this ?

**Comment by monora** [comment]
Just for completeness: See the [explanation in Wikipedia](https://en.wikipedia.org/wiki/Longest_path_problem[) why this a hard problem, which can not be solved efficiently using algorithms from RGL.
