### ISSUE TITLE
Check for a path between two vertices

### ISSUE THREAD

**Issue by smithtim** [monora/rgl#42]
Is there a method to check whether a path exists between two vertices?

E.g. `graph.path? v1, v2`

**Comment by monora** [comment]
You can use BFS or DFS graph iterator to get the answer:

 ```ruby
require 'rgl/adjacency'
require 'rgl/traversal'

module RGL::Graph
  def path?(v1, v2)
     # create BFS Iterarator starting from 1
     it = self.bfs_iterator(v1)
     # Use method any? of Enumerable
     it.any?(v2)
  end
end

dg=RGL::DirectedAdjacencyGraph[1,2 ,2,3 ,2,4, 4,5, 6,4, 1,6]
dg.path?(1,5) 
=> true
dg.path?(5,1)
=> false
```

Each _GraphIterator_ is a [Stream](https://www.rubydoc.info/github/monora/stream/Stream) which implements _Enumerable_:
```ruby
dg.bfs_iterator.class.ancestors
=> [RGL::BFSIterator, RGL::GraphVisitor, RGL::GraphIterator, RGL::GraphWrapper, Stream, Enumerable, Object, PP::ObjectMixin, Kernel, BasicObject]
```

**Comment by monora** [comment]
@smithtim does my answer help you? Can we close the issue?

**Comment by smithtim** [comment]
Yes, that helps, thanks!

If `v1` is not in the graph, it throws an exception.  This fixes that:

```ruby
module RGL::Graph
  def path?(v1, v2)
    # avoid exception if v1 is not in the graph
    return false if not self.has_vertex?(v1)
    # create BFS Iterator starting from v1
    it = self.bfs_iterator(v1)
    # Use method any? of Enumerable
    it.any?(v2)
  end
end
```

I am surprised that `path?` is not included in `RGL::Graph` by default.  Maybe it could be added?

**Comment by monora** [comment]
I would not add the method to the basic Graph API, because:

* I like to have small APIs which do the most basic stuff
* Graph module should not depend on module traversal.rb

You could add the method in this module extending module Graph. But that would also surprise people violating the POLS. 

I would rather add the code either in README or examples.rb. What do you think?

**Comment by smithtim** [comment]
I would be okay with having it in `traversal.rb`.  Maybe `traversal.rb` could be renamed `path.rb`?  Or maybe it could go in its own module?  Just throwing out some ideas.  I do think it should be part of the library, rather than something people have to copy-paste.

**Comment by monora** [comment]
I think we can put it in an own module `path.rb`. Would you like to contribute it?

**Comment by artkirienko** [comment]
Hi @monora,
Please check my PRs, I've tried both approaches: simply added info to the README, created a method in `path.rb`
