### ISSUE TITLE
Licence specification

### ISSUE THREAD

**Issue by hlascelles** [monora/rgl#43]
We have been asked to review the licences of gems we use. Can we get clarification of the licence for `rgl`? Thank you!

**Comment by monora** [comment]
RGL has the same license as the Ruby language. Quote from the README:

> Copying
RGL is Copyright (c) 2002,2004,2005,2008,2013,2015,2019 by Horst Duchene. It is free software, and may be redistributed under the terms specified in the README file of the Ruby distribution.

**Comment by hlascelles** [comment]
PR opened for the gemspec https://github.com/monora/rgl/pull/44.
