### ISSUE TITLE
undefined method `set_vertex_options' 

### ISSUE THREAD

**Issue by foolioo** [monora/rgl#98]
When I execute the snippet from https://github.com/monora/rgl/blob/master/README.md#optional-configuring-graphviz-dot-output-options  I get the follwing error

```shell
dot.rb:6:in `<main>': undefined method `set_vertex_options' for #<RGL::DirectedAdjacencyGraph:0x00000001044a3e18 @edgelist_class=Set, @vertices_dict={"a"=>#<Set: {"b", "c"}>, "b"=>#<Set: {}>, "c"=>#<Set: {"d"}>, "d"=>#<Set: {}>}> (NoMethodError)

graph.set_vertex_options('a', label: 'This is A', shape: 'box3d', fontcolor: 'green', fontsize: 16)
```

What am I missing?

**Comment by r0ckarong** [comment]
Are you on the master branch? If I remember correctly there isn't a proper release with this feature included as of now.

**Comment by r0ckarong** [comment]
@monora Could you make a new release please?

**Comment by monora** [comment]
I am currently in vacation. But I try.
